name: semo-test

services:
  semo-test:
    image: nginx:alpine
    container_name: semo-test
    restart: unless-stopped
    ports:
      - target: 80
        published: "5010"
        protocol: tcp

x-casaos:
  architectures:
    - arm64
    - arm
    - amd64
  main: semo-test
  category: Utilities
  icon: https://raw.githubusercontent.com/nanang2017/CasaOS-AppStore/main/Apps/semo-openclaw-demo/icon.png
  port_map: "5010"
  scheme: http
  index: /
  title:
    en_us: semo-test
  store_app_id: semotest