name: semo-openclaw-demo

services:
  semo-openclaw-demo:
    image: nginx:alpine
    container_name: semo-openclaw-demo
    restart: unless-stopped
    ports:
      - "5005:80"

x-casaos:
  main: semo-openclaw-demo
  title:
    en_us: semo-openclaw-demo
  category: Utilities
  icon: https://raw.githubusercontent.com/nanang2017/CasaOS-AppStore/main/Apps/semo-openclaw-demo/icon.png
  index: /
  port_map: "5005"